version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H19890123h
      POSTGRES_DB: api-app
    restart: always
    networks:
      - lesson
networks:
  lesson:
